server:
  port: 61

spring:
  application:
    name: ecloud-int-product-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.80.250:8848

  # 配置读写分离 & 分表
  shardingsphere:
    # 读写分离数据源：一主、一从
    datasource:
      names: d0,d1
      d0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
        url: jdbc:mysql://47.104.80.250:3306/ecloud_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: E@w123456
      d1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver        #mysql驱动包
        url: jdbc:mysql://47.104.80.250:3307/ecloud_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: E@w123456

    # 读写分离：
    rules:
      readwrite-splitting:
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
        data-sources:
          pr_ds:
            write-data-source-name: d0
            read-data-source-names: d1
            load-balancer-name: round_robin

    # 打开sql输出日志
    props:
      sql-show: true

  redis:
    database: 2
    #redis服务器地址
    host: 47.104.80.250
    #redis连接端口号
    port: 6379
    #redis连接密码
    password: ED888888
    #redis连接超时时间（毫秒）
    timeout: 10000

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #数据表的字段下划线转驼峰开启
  configuration:
    map-underscore-to-camel-case: true


dubbo:
  protocol:
    port: -1
  scan:
    base-packages: com.ec.product.service.impl
  registry:
    address: zookeeper://47.104.80.250:2181
