server:
  port: 61

spring:
  application:
    name: ecloud-int-product-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.247.85:8848

    # 配置读写分离 & 分表
  shardingsphere:
    # 读写分离数据源：一主、一从
    datasource:
      names: d0,d1
      d0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
        url: jdbc:mysql://47.104.247.85:3306/ecloud_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: E@w123456
      d1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
        url: jdbc:mysql://47.104.247.85:3307/ecloud_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: E@w123456

    # 配置分片。
    # 自带读写分离master-slave-rules：。
    sharding:
      master-slave-rules:
        d0:
          master-data-source-name: d0
          slave-data-source-names: d1

    # 打开sql输出日志
    props:
      sql:
        show: true


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #数据表的字段下划线转驼峰开启
  configuration:
    map-underscore-to-camel-case: true