server:
  port: 1001

spring:

  application:
    name: canal-consumer-sync-service-1001

  cloud:
    nacos:
      discovery:
        server-addr: 47.104.247.85:8848

  redis:
    database: 2
    #redis服务器地址
    host: 47.104.247.85
    #redis连接端口号
    port: 6379
    #redis连接密码
    password: ED888888
    #redis连接超时时间（毫秒）
    timeout: 10000
    # 高版本springboot中使用jedis或者lettuce
    lettuce:
      pool:
        # 连接池最小空闲连接
        min-idle: 1
        # 连接池最大空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1

rocketmq:
  name-server: 47.104.247.85:9876
  # 消费者配置
  consumer:
    # 与canal后台server管理canal.properties中，配置的rocketmq.producer.group一致
    group: canalsyncgroup #自定义。确保producer分布式下消息的一致，