server:
  port: 88

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ecloud-uid-generator-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.80.250:8848

  # 配置读写分离 & 分表
  shardingsphere:
    # 读写分离数据源：服务端多主多从，通过haproxy后，表现为一主、一从
    datasource:
      names: d0,d1
      d0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
        url: jdbc:mysql://47.104.80.250:3333/ecloud_uid_generator?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: E@w123456
      d1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver        #mysql驱动包
        url: jdbc:mysql://47.104.80.250:3334/ecloud_uid_generator?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: E@w123456

    # 读写分离：
    rules:
      readwrite-splitting:
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
        data-sources:
          pr_ds:
            write-data-source-name: d0
            read-data-source-names: d1
            load-balancer-name: round_robin

    # 打开sql输出日志
    props:
      sql-show: true

uid:
  timeBits: 30             # 时间位, 默认:30
  workerBits: 16           # 机器位, 默认:16
  seqBits: 7               # 序列号, 默认:7
  epochStr: "2022-01-05"   # 初始时间, 默认:"2021-12-20"
  enableBackward: true    # 是否容忍时钟回拨, 默认:true
  maxBackwardSeconds: 1    # 时钟回拨最长容忍时间（秒）, 默认:1
  CachedUidGenerator: # CachedUidGenerator相关参数
    boostPower: 3          # RingBuffer size扩容参数, 可提高UID生成的吞吐量, 默认:3
    paddingFactor: 50      # 指定何时向RingBuffer中填充UID, 取值为百分比(0, 100), 默认为50
    #scheduleInterval: 60    # 默认:不配置此项, 即不使用Schedule线程. 如需使用, 请指定Schedule线程时间间隔, 单位:秒

dubbo:
  scan:
    base-packages: com.ec.uid.service.impl
  protocol:
    port: -1
  registry:
    address: zookeeper://47.104.80.250:2181
