server:
  port: 91

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ecloud-int-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.80.250:8848 #配置Nacos地址
  redis: # redis-cluster 集群模式下，不支持切换数据库
    #redis连接密码
    password: ED888888
    #redis连接超时时间（毫秒）
    timeout: 10000
    cluster:
      nodes: 47.104.80.250:6379,47.104.80.250:6380,47.104.80.250:6381,47.104.80.250:6382,47.104.80.250:6383,47.104.80.250:6384

  # 配置读写分离 & 分表
  shardingsphere:
    # 读写分离数据源：服务端多主多从，通过haproxy后，表现为一主、一从
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
        url: jdbc:mysql://47.104.80.250:3333/ecloud_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: E@w123456
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
        url: jdbc:mysql://47.104.80.250:3334/ecloud_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: E@w123456

    # 读写分离：
    rules:
      readwrite-splitting:
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
        data-sources:
          msm:
            write-data-source-name: master
            read-data-source-names: slave
            load-balancer-name: round_robin

    # 打开sql输出日志
    props:
      sql-show: true



mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #数据表的字段下划线转驼峰开启
  configuration:
    map-underscore-to-camel-case: true