apiVersion: v1
kind: Service
metadata:
  name: account-service-service
  labels:
    app: account-service-service
spec:
  type: NodePort
  selector:
    app: account-service
  ports:
    - name: http
      protocol: TCP
      port: 2003 #service（对内）的端口
      targetPort: 2003 #pod的端口
      nodePort: 30003 #service（对外）的端口30000-32767。不指定随机分配。配合Ingress可分配对外端口
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service-container
          image: seata-account-service-2003:1.0  #镜像名称+版本
          imagePullPolicy: Never   #表示镜像来源，IfNotPresent本地没有就从hub仓库拉取，Never表示只从本地